### ISSUE TITLE
Should `@ampproject` be changed to `@bentoproject` in npm documentation?

### ISSUE THREAD

**Issue by rsimha** [ampproject/bentojs.dev#144]
For example, this section in https://bentojs.dev/get-started:
![Screen Shot 2021-12-07 at 11 27 55 AM](https://user-images.githubusercontent.com/26553114/144974665-fb1ee8a3-f1c6-4e1e-9343-6f382c9c80dd.png)

**Comment by kristoferbaxter** [comment]
Yes it should, good catch!
