### ISSUE TITLE
Typos and markdown artifacts tracking issue

### ISSUE THREAD

**Issue by rcebulko** [ampproject/bentojs.dev#151]
1. 
![image](https://user-images.githubusercontent.com/6694512/145257367-5523d652-c963-4de3-86f1-08fa267769c7.png)
2. 
![image](https://user-images.githubusercontent.com/6694512/145257390-0fc2b0ab-557b-44d4-9587-9f6d124d22a1.png)
3. 
![image](https://user-images.githubusercontent.com/6694512/145257414-bde0669d-60d0-4089-a167-31f725a2b7b6.png)

**Comment by rcebulko** [comment]
Syntax highlighting here appears to be using HTML, not JS(X):
![image](https://user-images.githubusercontent.com/6694512/145257542-a7b41d89-480c-4419-8edb-4285decb6265.png)

**Comment by rcebulko** [comment]
"Embedding a Tweer"
![image](https://user-images.githubusercontent.com/6694512/145257614-50cccbd7-09e5-4a0c-b99f-ef995796d97f.png)

**Comment by rcebulko** [comment]
![Uploading image.png…]()

**Comment by rcebulko** [comment]
nit: Different conventions for 3p
![image](https://user-images.githubusercontent.com/6694512/145257836-b9992a2e-12bc-4b14-b008-5429cd093de1.png)

**Comment by rcebulko** [comment]
Reopening for visibility since it was closed right as I was adding another comment, fell free to re-close (and sorry for the noise)
 if all are addresed

**Comment by sebastianbenz** [comment]
Fixed in main

**Comment by sebastianbenz** [comment]
Thanks @rcebulko !
