### ISSUE TITLE
[Bikeshed]: `<bento-fit-text>` as part of the title seems like a mistake

### ISSUE THREAD

**Issue by samouri** [ampproject/bentojs.dev#168]
**summary**
I believe including `<bento-fit-text>...</bento-fit-text>` as part of the title is meant to be cute...and it is! I unfortunately think it can too easily come across as a coding error. We've all seen improper serialization/deserialization of HTML tags and/or character entities so often that I believe most will assume thats the case here as well.

I think the post reads better as simply "Hello World!"

**screenshots**
![Screen Shot 2022-01-19 at 9 30 56 AM](https://user-images.githubusercontent.com/4656974/150151386-3e096f95-1829-4d82-983f-da078096d3e6.png)
![Screen Shot 2022-01-19 at 9 31 02 AM](https://user-images.githubusercontent.com/4656974/150151395-62471fe9-513f-48aa-a342-e5698eb3f5ce.png)

**Comment by sebastianbenz** [comment]
I have no strong opinion here. Happy to change the title (`Introducing the Bento component library` would be my suggestion). Another option would be to publish many more blog posts so that this one moves further to the back ;-).
